// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayictyqbzkybzybjvcgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5aWN0eXFiemt5Ynp5Ymp2Y2dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MTY4NDQsImV4cCI6MjA2MTE5Mjg0NH0.7R-AwcDbSdxrQxUeYtrt9FCApIdV_yQa3F9Z9d3dpfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);