// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dysrpbsnjjdpldjnntsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5c3JwYnNuampkcGxkam5udHNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzNjEwOTgsImV4cCI6MjA3OTkzNzA5OH0.YdcNLbltePwpXJfWii8EuUTWlh-S2Hj7pbuH7sK_0zw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
